### ISSUE TITLE
Beta 2.7.1.0-caa41fe5 (bug issue #4) freezes on startup after bug issue #5 is available

### ISSUE THREAD

**Issue by Firekorn** [rscustom/rocksmith-custom-song-toolkit#266] opened 2016-10-15 09:30 UTC
Since the new version of the beta is available, the toolkit completely freeze right after startup and can't be used at all. It was working fine before the new beta version was pushed.

The update executable don't actually update anything and it's impossible to update the toolkit within the tool itself.

Sadly the log gives me a "access denied" so i'm not sure what more information could i provide in a situation like this.

**Comment by cozy1** [comment] 2016-10-15 13:31
I down loaded beta version 2.7.1.0 (rev 9ec31e2c) from [here](https://www.rscustom.net/download/605/rstoolkit-2.7.1.0-9ec31e2c-win.zip)
and am unable to reproduce your issue.  What have you tried to fix on your end?  

1) Log in as admin
2) Add toolkit (RocksmithToolkitGUI.exe) to your AV's whitelist (approved apps)
3) Completely uninstall toolkit
4) Download the latest version of toolkit.
5) Unzip toolkit to the default folder (rstoolkit-2.7.1.0-xxxxxxxx-win) and leave it there
6) Run it and enjoy.

**Comment by Firekorn** [comment] 2016-10-15 18:12
First i don't have issue when using the 9ec31e2, i have issue on the caa41fe4 (100% bug issue #4).
This makes me thing that it's somehow linked to the fact there's a newer version available and this issue won't appear on the last version of the toolkit.

1) As an admin i get the same result
2) The AV only unlocked the updater, but the toolkit is still freezing right after start up
3 to 6) i'm not sure where would that get you for finding why the toolkit freeze when there's a newer version available and i'm already using the last version for creating CDLC.

**Comment by Firekorn** [comment] 2016-10-16 15:36
Well now even 9ec31e2 freeze causes there's a newer version available... As long as i don't use the creator tab everything seems to works fine, but if i go back the creator tab or try to use any of the button on the creator tab, the toolkit freeze and i have to kill the process...

**Comment by cozy1** [comment] 2016-10-18 00:52
Are you are on Windows 10?   Did you install the required version of .Net?

**Comment by Firekorn** [comment] 2016-10-18 09:30
I am on W10 and i do have the required version of .Net

**Comment by L0FKA** [comment] 2016-10-20 10:37
Fix is manually download lates toolkit, bug fixed by now.

**Comment by Firekorn** [comment] 2016-10-20 12:30
So your auto-updater is completely broken and make the toolkit freeze when he find a new version and the only "fix" you suggest is to download the new version manually?

No offense but that is the worst "fix" i could have hoped for...

**Comment by L0FKA** [comment] 2016-10-20 13:57
@Firekorn, just had this issue, so I guess it may be something related to version ifo logic, gotta play with it tonight, seems nothing fixed yet, sorry :*I

**Comment by Unleashed2k** [comment] 2016-10-20 20:51
I can confirm same issue on windows 10. Getting messages from other people about it too.

**Comment by ray** [comment] 2016-10-20 21:55
This was caused by the new dialog message added in a49c232: https://github.com/rscustom/rocksmith-custom-song-toolkit/blob/a49c23221908b900c8d250ec00dfaeb407be1a33/RocksmithTookitGUI/MainForm.cs#L40-L50

For some reason that's causing thread errors and just hangs. You should see the error when debugging
```
Application.ThreadException
System.InvalidOperationException: Cross-thread operation not valid: Control 'MainForm' accessed from a thread other than the thread it was created on.
...
   at RocksmithToolkitGUI.MainForm.EnableUpdate(Object sender, RunWorkerCompletedEventArgs e) in \RocksmithTookitGUI\MainForm.cs:line 115
```

I've disabled that dialog for now and it seems to fix the issue.

**Comment by ray** [comment] 2016-10-20 22:01
I've also disabled updates for the affected builds from a49c232 to 667ffac on the server side to stop them from hanging, users will need to update manually and won't get a notification

**Comment by cozy1** [comment] 2016-10-20 23:58
@ray I would like to have discussion with you in private about the server.  Can you contact me on google hangouts?

**Comment by L0FKA** [comment] 2016-10-21 05:10
True was near, plus that popup window has ugly bitmaps at w10

**Comment by cozy1** [comment] 2016-10-26 16:33
@L0FKA Plz confirm updater is working again with latest beta revision and close this issue if fixed.

**Comment by L0FKA** [comment] 2016-10-27 09:22
@cozy1, that message still causing hang(for a short time, like 2 minutes)+crush then for updater, but updater is fail to run with ray's fix too... still not fixed, sorry.

**Comment by cozy1** [comment] 2016-10-27 13:54
@L0FKA So what may need to happen then is to move the beta popup message after the updater does its thing.  Could you give that a try?  Thanks

**Comment by cozy1** [comment] 2016-10-27 15:19
@ray  I believe the updater issues have to do with changing the server from http:// to https://.  Could you switch server back to http:// so that devs could debug the updater.

**Comment by ray** [comment] 2016-10-27 15:32
It's been https for 2 years now

**Comment by cozy1** [comment] 2016-10-27 17:22
I am on WinXp dev machine which does not support TLS 1.2 which is required to download from https:// server.  So I can not help debug.  Apparently it is more than just the new beta popup causing problem with updater.  I eliminated cross thread issue and put in multiple connection attempts but there still seems to be a problem.

**Comment by ray** [comment] 2016-10-27 18:37
XP should be able to fail back to TLS 1.0. The only thing that should prevent it from working is if a client doesn't support SNI (like IE), but I would think that support in the app would depend on .NET rather than the OS.

In any case, the issue is the same as before:
```
Application.ThreadException
System.InvalidOperationException: Cross-thread operation not valid: Control 'MainForm' accessed from a thread other than the thread it was created on.
...
   at RocksmithToolkitGUI.MainForm.EnableUpdate(Object sender, RunWorkerCompletedEventArgs e) in rocksmith-custom-song-creator\RocksmithTookitGUI\MainForm.cs:line 101
```

This is now fixed in the latest commit by swapping the order of InitMainForm() and ShowHelpForm()

**Comment by L0FKA** [comment] 2016-10-27 18:44
Cozy don't really like to investigate what's root of issue is :D 
baf 🗡

**Comment by cozy1** [comment] 2016-10-27 22:06
@ray I have looked into this quite a bit and I could be wrong but I don't think so.  https://blogs.msdn.microsoft.com/kaushal/2011/10/02/support-for-ssltls-protocols-on-windows/

Also if you hit the server with firefox (a TLS 1.2 compliant browser) it will tell you that the server is requesting TLS 1.2.  WinXp is not able to do this.  It was never designed for it.  So it is problem with my old dev system.  ;(

**Comment by cozy1** [comment] 2016-10-27 22:11
@ray @L0FKA  MainForm.cs Line 101 has nothing to do with the beta message popup.  https://github.com/rscustom/rocksmith-custom-song-toolkit/blob/master/RocksmithTookitGUI/MainForm.cs#L101  Has to do with the worker most likely which would explain threading issue.  May need to invoke.

**Comment by ray** [comment] 2016-10-27 22:30
The error started when the popup was added, and went away when the popup was moved to after the form is initialized. The issue is fixed now.

**Comment by L0FKA** [comment] 2016-10-28 05:16
I think combination of loading events + one extra message at the top caused some black magic that eat lot's of resources, I'm able to runover that at i5 6600k, but at my dev system that would be like 8 times longer

there is updater bgworker, then, MainForm_Load then MainForm_Shown plus it has some config tab removal\opening logic, I think this is part of the issue for mac toolkits, which had similiar issue with long first run issue, maybe we should redesign loading part to solve unexpected issues with managed threads .__.

**Closed** 2016-11-12 16:15 UTC
