### ISSUE TITLE
Automatically add NDD at the end of the file name even if DD has been created in EOF

### ISSUE THREAD

**Issue by Firekorn** [rscustom/rocksmith-custom-song-toolkit#271] opened 2016-10-27 17:40 UTC
I create DD by hand inside EOF and i now need to delete the "NDD" part of the file because of the new naming convention of the revision 6c081a48

Can we at least get to choose if we want that naming convention to be applied or not?

**Comment by cozy1** [comment] 2016-10-27 18:14
Toolkit can give you choice like you ask for, or it can automatically detect if DD is present or not from EOF and then name CDLC accordingly NDD or DD.  Maybe DD and NDD naming are not important anymore since all CDLC must have DD to work correctly with remastered. Which would you like?

**Comment by Firekorn** [comment] 2016-10-27 18:19
Doesn't really matters to me, as long as i don't have to make sure the naming of the CDLC i create is correct every single time i generate it :)

I guess the "best" solution would be for the name to adapt to the xml file content as it would be more reliable for everyone no matter how people create DD.

About DD being a necessity in Remastered, it would require some actual investigation but probably for what i've seen so far (mostly regarding the play count that seems to not increment if there's 0 level of difficulty instead of only needed section before the update)

**Comment by cozy1** [comment] 2016-10-30 21:42
@Firekorn   Added new feature.  If DD is already present in an arrangement then the 'CDLC Creator' will not overwrite the existing DD even if the 'Auto Generate DD' checkbox is checked in 'General Config'.  Feature added for charters who add DD in EOF.  Plz test and let us know if it works for you.

**Comment by Firekorn** [comment] 2016-11-05 19:23
@cozy1 Well the naming indeed seems to work as intended (want to try how it react if one file has DD but not another just in case) but i get this error when trying to generate the CDLC so i prefer to wait for this to be resolved first :)
![toolkiterror](https://cloud.githubusercontent.com/assets/1771169/20032811/d17b26be-a392-11e6-8dde-1d363bfa80e7.png)

Here are the files for used on that screenshot : https://drive.google.com/drive/folders/0B1ZKYtpB0vu2d1JHaFJOWmpGeFk?usp=sharing

I only used the PART REAL_GUITAR_22_RS2 and the vocals (the tones are the one that start with niclas) I haven't tried with anything else yet but the other part don't have DD in them (yet).

Side note : i haven't tested if the automated generation is also stopped yet.

**Comment by cozy1** [comment] 2016-11-10 14:37
I was able to reproduce the errors and fix them.  See latest beta release.  https://www.rscustom.net/

**Comment by Firekorn** [comment] 2016-11-12 13:00
@cozy1 Everything seems in order to me with 836b6135 👍

**Closed** 2016-11-12 13:01 UTC
