### ISSUE TITLE
Convert to RS1 > RS2014 "thread exception catched"

### ISSUE THREAD

**Issue by DindonNinja** [rscustom/rocksmith-custom-song-toolkit#252] opened 2016-02-13 18:20 UTC
Hello,

I was trying to convert a RS1 song to RS2014 using the Import package option. I chose the .dat file, clicked Generate, the loading bar goes halfway and then a "Thread Exception Catched" window popped. 

The content of my crash log is:

2016-02-13 19:04:28.7356 | RocksmithToolkitGUI.Program (INFO) : 
 RocksmithToolkitGUI.Program.Main 
 Version: 2.6.1.0-6265b2e4 (32 bit)
 OS: Microsoft Windows NT 6.2.9200.0 (64 bit)
 Runtime: v4.0.30319.34014
 JIT: MsX86 

2016-02-13 19:08:54.8335 | RocksmithToolkitGUI.Program (ERROR) : 
 RocksmithToolkitGUI.Program+<>c.<Main>b__1_1 
 
System.Core
TSource First[TSource](System.Collections.Generic.IEnumerable`1[TSource], System.Func`2[TSource,System.Boolean])
Exception catched:

 
System.InvalidOperationException Sequence contains no matching element TSource First[TSource](System.Collections.Generic.IEnumerable`1[TSource], System.Func`2[TSource,System.Boolean])    at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at RocksmithToolkitLib.DLCPackage.DLCPackageData.RS1LoadFromFolder(String unpackedDir, Platform targetPlatform, Boolean convert) in C:\projects\rocksmith-custom-song-toolkit\RocksmithToolkitLib\DLCPackage\DLCPackageData.cs:line 199
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.dlcImportButton_Click(Object sender, EventArgs e) in C:\projects\rocksmith-custom-song-toolkit\RocksmithTookitGUI\DLCPackageCreator\DLCPackageCreator.cs:line 801
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam) System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at RocksmithToolkitLib.DLCPackage.DLCPackageData.RS1LoadFromFolder(String unpackedDir, Platform targetPlatform, Boolean convert) in C:\projects\rocksmith-custom-song-toolkit\RocksmithToolkitLib\DLCPackage\DLCPackageData.cs:line 199
   at RocksmithToolkitGUI.DLCPackageCreator.DLCPackageCreator.dlcImportButton_Click(Object sender, EventArgs e) in C:\projects\rocksmith-custom-song-toolkit\RocksmithTookitGUI\DLCPackageCreator\DLCPackageCreator.cs:line 801
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

What does it mean please, and is there any way to fix it? :)

Thanks!

-DindonNinja

**Comment by L0FKA** [comment] 2016-02-13 18:28
I see, gotta check it out!

It was pretty unstable last time I used it, thanks for the report

**Comment by DindonNinja** [comment] 2016-02-13 18:32
No problem, there's a great work on the toolkit, keep going guys!

**Comment by cozy1** [comment] 2016-02-13 19:51
Some RS1 dat files can not be converted.  I just check RS1 converted and can not reproduce your error.  Can you provide link via CF PM to the file you are trying to convert?  DO NOT post a link to file here.

**Comment by DindonNinja** [comment] 2016-02-13 22:40
I did sent a PM on CF.

**Comment by cozy1** [comment] 2016-02-14 16:15
RS1 converter in toolkit is working as intended.  It is known flaw that not all RS1 can be converted.  Closing issue after having PMd with originator.

**Closed by cozy1** 2016-02-14 16:15 UTC
Labels: bug
