### ISSUE TITLE
(Mac) Mono 5.14.0 + RSToolKit (latest and latest recommended) --> "Need 2.8 or higher"

### ISSUE THREAD

**Issue by kfeuerherm** [rscustom/rocksmith-custom-song-toolkit#327] opened 2018-10-08 15:20 UTC
Using macOS High Sierra 10.13.6 (17G2307).

As per instructions on [Customs Forge](http://customsforge.com/index.php/topic/33889-how-to-add-custom-songs-on-mac/page-1) installed latest Mono.

Could not run from terminal so added "/Library/Frameworks/Mono.framework/Versions/Current/Commands" to /etc/paths, now seems to work.

Tried both 2.9.0.0 (rev b1c03443) and 2.9.1.0 (75a42866) [among other things] but either way only get an error message saying I need Mono 2.8 or higher.

No idea what's wrong here? No response on Customs Forge so far.
<img width="623" alt="screen shot 2018-10-08 at 11 12 26" src="https://user-images.githubusercontent.com/11524091/46617859-d6858500-caeb-11e8-8192-3e786a9c646f.png">
<img width="422" alt="screen shot 2018-10-08 at 11 11 49" src="https://user-images.githubusercontent.com/11524091/46617870-e00eed00-caeb-11e8-9135-e504f8f3fd7e.png">

**Comment by cozy1** [comment] 2018-10-09 00:59
Did you install the [RSInjector](https://github.com/rscustom/RSInjector-Mac/releases/tag/v1.1)?  [Thi](https://www.youtube.com/watch?v=RssYfULpLZ4)s may help.  Please let us know if you get it working.

**Comment by kfeuerherm** [comment] 2018-10-09 02:57
I wondered about that too... I understood we don’t need it any more. Certainly I’ve not used it in a long time.

**Comment by kfeuerherm** [comment] 2018-10-09 17:13
Ok so...

1) the folks on Custom Forge say that Mono soon won't work at all, whatever that means (and they sound like it doesn't work well now)

2) Somebody produced some version of the [toolikit for Mac](http://customsforge.com/index.php/topic/39922-latest-rstoolkitmac-releases-9-20-2018/page-4#entry294399) which seems to run, though I've not tried it yet

3) So I'd got rid of Mono but I'll do some tinkering once I have it reinstalled.

Yes, I forked because I had a sabbatical year (I teach university) and planned to play with all this but my computer died and was only replaced after the sabbatical was over, so now I'm crazy busy! Typical, eh?

**Comment by JustinAiken** [comment] 2018-10-09 18:27
Yes, it works w/ mono for me on Sierra

**Comment by kfeuerherm** [comment] 2018-10-09 19:08
I didn’t say either of you.. it was on Customs Forge. I don’t know what it is used for here anyway.

I’ve got it reinstalled now, playing with the package script now. Not well versed in bash though so have to think on it.

**Comment by kfeuerherm** [comment] 2018-10-09 20:38
I looked at the script pointed to by @L0FKA and didn't see any problem with the test, but to be sure, I copied lines 1--41 and added a few lines (see attached, not sure how we deal with code here?)
[monoscript.txt](https://github.com/rscustom/rocksmith-custom-song-toolkit/files/2462054/monoscript.txt)

Output as follows (as expected, no snotty message):

$MONO_VERSION:        5.16.0.179
$MONO_VERSION_MAJOR:  5
$MONO_VERSION_MINOR:  16

So seems to me the test works. And if I replace line 28 with `MONO_VERSION="2.7.99"` then I get the box (again, as expected). So

1) why does it not work as part of the package?
2) note that the download url is wrong. Should probably be [this](https://www.mono-project.com/download/stable/)?

**Comment by L0FKA** [comment] 2018-10-10 05:12
Oh I'm talking here and there, and my statement over CustomsForge that mono is a relic... it is a relic for now until we've got fully featured NetCcore framework working under mac (since it's all microsoft domain)

but for a while I'm able to figure out what's wrong to the launcher\toolkit itself so we could figure it out faster, but for Justin all works since he's mainly CLI user and able to fix minor issues himself, what happens when you comment out that if statement from the script code inside your downloaded .zip file with app (inside of that package, not your own copy off toolkit code)

probably there's issue with closing ' [' operands  idk key -a tests for a file to exist on disc so it's basically wrong it won't join those statements, I'm not a bash wizard but bash man says so :)

**Comment by kfeuerherm** [comment] 2018-10-10 14:57
Ok, so downloaded the latest build and found the bash file, played with it.

This line `MONO_VERSION="$(mono --version | grep 'Mono JIT compiler version ' |  cut -f5 -d\ )"` is not working, MONO_VERSION is an empty string, that's why the test is failing. Even though this script works in my terminal, it doesn't work within the package.

I already know that the Mono installer does not set the path to work in terminal, so maybe this script is not picking up my fix.

I'll see what happens if I just delete the test (but I don't think that's really a fix, just a kludge at best).

**Comment by kfeuerherm** [comment] 2018-10-10 15:22
Did some more tests. With dialog boxes placed here and there, I found out this:

PWD      = /
APP_PATH = /Applications/RocksmithCustomSongToolkitTest.app/
APP_NAME = RocksmithCustomSongToolkit
ASSEMBLY = RocksmithCustomSongToolkit.exe
MWF_MODE = 1

I assume that's normal. It just isn't picking up the Mono version as I said in the previous comment.

Also, if I patch the Mono version manually instead of using the grep, then I don't get the error, but nothing loads at all, nothing happens. So presumably Mono isn't being found even though it is installed and I can find it in Terminal.

**Comment by JustinAiken** [comment] 2018-10-10 15:52
I had installed mono via `brew cask install mono-mdk` and it just worked - didn't manually mess with my path or anything

**Comment by kfeuerherm** [comment] 2018-10-10 15:58
Ok... well, the instructions point to the Mono site to do a direct installation, and clearly that requires manual intervention. So it would be good to know what your paths are set to, then. Can you tell me what you have in /etc/paths? and maybe a listing of the directories specified there? (actually, only if they have a reference to mono I guess).

I'm thinking that Homebrew will have put a pointer somewhere, it's just a question of finding out where. The manual patch I made isn't being picked up by the toolkit installer.

(I'm sort of new to this level of detail but I'm learning :) I'd prefer to know exactly what is different than relying on Homebrew to fix it in the background....)

**Comment by JustinAiken** [comment] 2018-10-10 16:00
Looks like it mostly just installs the pkg: 

https://github.com/Homebrew/homebrew-cask/blob/d5b10908d1a6acedfdd754335237f8c7ce9e78f9/Casks/mono-mdk.rb#L10

But it's the `mono-mdk` package, not just the base `mono` package

**Comment by kfeuerherm** [comment] 2018-10-10 16:02
Thanks, I'll look into that. Clearly the instructions need a tidy-up!!

**Comment by Firekorn** [comment] 2018-10-10 16:05
As far as i'm concern those instructions are out of date and i don't know any mac user willing to take care of that post as the ones that created it doesn't seems to be around anymore to adjust it in any way.

I've made sure that this post is correct regarding the mac patch for CDLC to work but that's as far as i deal with mac myself but if anyone have something to suggest, i'll be willing to change the post accordingly to more appropriate instructions.

**Comment by kfeuerherm** [comment] 2018-10-10 16:08
You're quite right.

I've just found the MDK location so if I can get this thing working I will be happy to rewrite the instructions....

Worst case, if we can't get this working the 'traditional way', it might be best to delete those instructions and just put a pointer to your patched version....

Anyway, I'm working on it (with a little help from my friends :) )

**Comment by kfeuerherm** [comment] 2018-10-10 16:12
Arg! That's the same as the one I downloaded in the first place. So @JustinAiken, I'm back to square one. Need to figure out where the path is being set.

**Comment by kfeuerherm** [comment] 2018-10-10 16:38
Ok, so I installed Mono 5.14.0.177 as suggested by the cask script, after removing my patch from /etc/path.

That installer clearly does something that the later ones do not do, since `mono` is available from the terminal without any manual patching. But that's not the end of it, I still get the error.

So @JustinAiken, can you tell me which build of the `rstoolkit` you are using?

**Comment by kfeuerherm** [comment] 2018-10-10 16:44
And as far as I can see, I'm limited in testing since the [builds page](https://www.rscustom.net/builds) which supposedly has the older versions doesn't really go back past 2.9....

**Comment by cozy1** [comment] 2018-10-10 16:53
All builds can be found [here](https://github.com/rscustom/rocksmith-custom-song-toolkit/releases).

**Comment by JustinAiken** [comment] 2018-10-10 16:59
> So @JustinAiken, can you tell me which build of the rstoolkit you are using?

Ooh, haha, I hadn't updated for a few months - it is broken for me too (running the main app... `wine`'ing the indiviudal CLI tools still works)

Let me poke, I bet I can come up with a fix..

**Comment by L0FKA** [comment] 2018-10-10 17:11
@JustinAiken  what's different `brew install mono` vs `brew cask install mono-mdk`  if I'll do auto install thing withing this script?

also let's try to reproduce some more issues you've met here :)

**Comment by JustinAiken** [comment] 2018-10-10 17:34
Okay, two things I've found..

- On mono being detected:
  - If I run from my terminal, via `open /Applications/RocksmithCustomSongToolkit.app/Contents/MacOS/RocksmithCustomSongToolkit`, it finds it and knows what version it is
  - But if I just click the icon, it exits
  - Looks like my PATH in the terminal has `/Library/Frameworks/Mono.framework/Versions/Current/Commands` 

- It segfaults immediately, because mono now defaults to 64bit.  If you which `which mono` for `which mono32`, then it comes up and works.
  - You could also do `mono --arch=32`

**Comment by L0FKA** [comment] 2018-10-10 18:32
Oh, toolkit is fine with mono32 and mono64 bit as far as I know, it's ok running both actually, weird thing that it's failing on startup tho...

**Comment by kfeuerherm** [comment] 2018-10-10 20:17
Ok, I've determined so far (due to lack of time haven't done more) that the current Mac build doesn't work at all, while 2.8.4 starts to run but then aborts on Mono (a small step forward)....

**Comment by L0FKA** [comment] 2018-10-10 20:18
I'm currently trying to play with that on my VM sierra(not high sierra tho) gotta see if there any flaws with latest build myself :)

**Comment by kfeuerherm** [comment] 2018-10-10 20:31
I’ll be interested to hear what you find.

I just got the invite for Mojave, but I’m putting that off as I’m in the middle of teaching a digital class and the last thing I need is unexpected errors….

**Comment by L0FKA** [comment] 2018-10-14 08:54
I've find a better way to deliver mono to the system using brew and I'll change that so you've got mono installed right, probably I'll change that -a test in if part so it won't mess with me and bash next thing would be installing wine using brew cask and fixing path if required, that should permfix any issues in future related un-installed or missing mono in path variable. Also would like to test if mono would hook up to wine or how to set up macOS to raun any .exe using wine :thinking:

**Comment by L0FKA** [comment] 2018-11-30 20:56
I have script ready to be tested(sort of) and I need a clean macOS to play with brew-cask is the way to do it for new users w\o mono...

**Comment by kfeuerherm** [comment] 2018-11-30 22:57
Great to hear! But as I mentioned earlier, sometimes we’re forced into a mono installation. What then?

**Comment by L0FKA** [comment] 2018-12-10 19:42
If you manually install mono it may fail to find it also cold be really issue with script not looking for mono32 that would return false information about mono presence...
installing mono through brew eliminate need to manually download it from site. also I should just push it and se what's happens side note I can't properly test popup window written using osacript so I'll autoinstall mono without asking user....

**Comment by cozy1** [comment] 2020-02-13 13:41
closing this.  plz use toolkit mac wine port version which has support for up to mac os high sierra: http://ignition.customsforge.com/cfsm_uploads/rstools_mac/RocksmithTools.dmg

**Closed by cozy1** 2020-02-13 13:41 UTC
